export const state = {
  INIT: "INIT",
  LOADED: "LOADED",
  UPLOADING: "UPLOADING",
  UPLOADED: "UPLOADED",
  ERROR_UPLOADING: "ERROR_UPLOADING",
  COMPLETED: "COMPLETED",
  RECORDING: "RECORDING",
};
